language: node_js
node_js:
    - "6"
env:
    - MY_VAR=n
before_script:
    - npm install
sudo: false
cache:
    directories:
        - node_modules
script:
    - npm test
after_success:
    - bash <(curl -s https://codecov.io/bash)
deploy:
    provider: script
    script: scripts/deploy.sh
    on:
        branch: deploy
