language: node_js
node_js:
    - "6"
env:
    - MY_VAR=nope
before_script:
    - npm install
sudo: false
cache:
    directories:
        - node_modules
script:
    - gulp build-for-production
    - npm test
after_success:
    - bash <(curl -s https://codecov.io/bash)
