language: node_js
node_js:
    - "node"
    - "6"
env:
    - MY_VAR=EverythignIsAwesome
    - NODE_ENV=TEST
before_script:
    - npm install
sudo: false
cache:
    directories:
        - node_modules
script:
    - gulp build-for-production
    - npm test
