language: node_js
node_js:
    - "6"
env:
    - MY_VAR=nope
before_script:
    - npm install
sudo: false
cache:
    directories:
        - node_modules
script:
    - gulp build-for-production
    - npm test
after_success:
    - bash <(curl -s https://codecov.io/bash)
    - npm install
    - mkdir build
    - mv * build
    - tar -czf package.tgz build
    - scp package.tgz $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
